---
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: SSL://:9093,SASL_SSL://:9094
      KAFKA_ADVERTISED_LISTENERS: SSL://:9093,SASL_SSL://:9094
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: "SSL"
      KAFKA_SSL_CLIENT_AUTH: "required"
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/data/kafka.server.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "123123"
      KAFKA_SSL_KEYSTORE_LOCATION: "/data/kafka.server.keystore.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: "123123"
      KAFKA_SSL_KEY_PASSWORD: "123123"
      KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/data/kafka_server_jaas.conf"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
